### ISSUE TITLE
rust_str! macro needs to check for null ptrs

### ISSUE THREAD

**Issue by glowkey** [mikelodder7/rust-indy-sdk#2]
For example, in the indy_issuer_create_credential() callback the second and third strings can be null if no revocation is used.

**Comment by mikelodder7** [comment]
So would you want the Rust code to use Option with a None for null?

**Comment by glowkey** [comment]
Yes, that sounds great.

**Comment by mikelodder7** [comment]
Fixed by commit f718c3516a4bc4c4ea57bf6c9d687c8ae9298740
