### ISSUE TITLE
Redundant structs

### ISSUE THREAD

**Issue by vimmerru** [mikelodder7/rust-indy-sdk#4]
For the current moment all API functions implemented as static structs methods in dedicated submodule. It causes unnecessary usage of structs in code. We can just have public functions in submodule:

```
indy::wallet::Wallet::create("{}", "{}").unwrap();
```

can be just replaced with 

```
indy::wallet::create("{}", "{}").unwrap();
```

It will look much more nature to Rust.

**Comment by mikelodder7** [comment]
Let’s move this to [here](https://github.com/evernym/rust-libindy-wrapper)
